CREATE TABLE Users
(
	UserID INT PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(50),
	Password VARCHAR(50),
	Email VARCHAR(100)
);

CREATE TABLE Posts
(
	PostID INT PRIMARY KEY IDENTITY(1,1),
	Image VARCHAR(250),
	Caption VARCHAR(250),
	Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	UserID INT
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Likes
(
	LikeID INT PRIMARY KEY IDENTITY(1,1),
	Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	PostID INT,
	UserID INT,
	FOREIGN KEY (PostID) REFERENCES Posts(PostID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Comments
(
	CommentID INT PRIMARY KEY IDENTITY(1,1),
	CommentText VARCHAR(250),
	Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	PostID INT,
	UserID INT,
	FOREIGN KEY (PostID) REFERENCES Posts(PostID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Shares
(
	ShareID INT PRIMARY KEY IDENTITY(1,1),
	Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	PostID INT,
	UserID INT,
	FOREIGN KEY (PostID) REFERENCES Posts(PostID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);